# Generated by Django 4.2.11 on 2024-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Model', models.CharField(max_length=50)),
                ('FinalGrade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
